SoloGuide/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.urls import path
from . import views
from .views import CustomLoginView, RegisterPage, GuideCreate, GuideUpdate, GuideDelete, DetailView, GuideReview
from django.contrib.auth.views import LogoutView
app_name = 'blog'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='blog:home'), name='logout'),
    path('register/', RegisterPage.as_view(), name='register'),

    path('guide-create/', GuideCreate.as_view(), name='guide-create'),
    path('guide-review/', GuideReview.as_view(), name='guide-review'),

    path('', views.home, name='home'),
    path('articles/', views.articles, name='articles'),
    path('<slug:article>/', views.article, name='article'),
    path('<slug:slug>/guide-update/', GuideUpdate.as_view(), name='guide-update'),
    path('<slug:slug>/guide-delete/', GuideDelete.as_view(), name='guide-delete'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    profile_pic = models.ImageField(null=True, blank=True, upload_to="profile")
    bio = models.TextField(null=True, blank=True)

    def __str__(self):
        name = str(self.user)
        return name


class ArticleManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='usernames'
    )
    headline = models.CharField(max_length=200)
    sub_headline = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(null=True, blank=True, upload_to="article", default="placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True)

    options = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    publish = models.DateTimeField(default=timezone.now)

    status = models.CharField(max_length=10, choices=options, default='draft')

    objects = models.Manager()  # default manager
    articlemanager = ArticleManager()  # custom manager

    def get_absolute_url(self):
        return reverse('blog:article', args=[self.slug])

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.headline

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Profile, Tag, Article, User
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.views.generic import DetailView, TemplateView
# Login / register
from django.contrib.auth.views import LoginView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
# Create your views here.


class CustomLoginView(LoginView):
    template_name = 'login.html'
    fields = '__all__'
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('blog:home')


class RegisterPage(FormView):
    template_name = 'register.html'
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy('blog:home')

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('blog:home')
        return super(RegisterPage, self).get(*args, **kwargs)


def home(request):

    # feature articles on the home page
    featured = Article.articlemanager.filter(featured=True)[0:6]

    context = {
        'articles': featured
    }

    return render(request, 'index.html', context)


def articles(request):

    # get query from request
    query = request.GET.get('query')
    # print(query)
    # Set query to '' if None
    if query == None:
        query = ''

    # articles = Article.articlemanager.all()
    # search for query in headline, sub headline, body
    articles = Article.articlemanager.filter(
        Q(headline__icontains=query) |
        Q(sub_headline__icontains=query) |
        Q(body__icontains=query)
    )

    tags = Tag.objects.all()

    context = {
        'articles': articles,
        'tags': tags,
    }

    return render(request, 'articles.html', context)


def article(request, article):

    article = get_object_or_404(Article, slug=article, status='published')

    context = {
        'article': article
    }

    return render(request, 'article.html', context)


class GuideCreate(LoginRequiredMixin, CreateView):
    model = Article
    fields = ['headline', 'sub_headline', 'image', 'body']
    template_name = 'guide_form.html'
    success_url = reverse_lazy('blog:guide-review')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(GuideCreate, self).form_valid(form)


class GuideUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ['headline', 'sub_headline', 'image', 'body']
    template_name = 'guide_form.html'
    success_url = reverse_lazy('blog:articles')

    def test_func(self):
        article = self.get_object()
        if self.request.user.id == article.author.id:
            return True
        return False


class GuideDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    context_object_name = 'article'
    template_name = 'guide_delete.html'
    success_url = reverse_lazy('home:articles')

    def test_func(self):
        article = self.get_object()
        if self.request.user.id == article.author.id:
            return True
        return False


class GuideReview(LoginRequiredMixin, TemplateView):
    template_name = 'review_message.html'

blog/templates/article.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--==========================
    Intro Section
    ============================-->
    <section id="intro--each"
             style="background: url({{ article.image.url }}) top center; background-size: cover;">
      <div class="intro-container wow fadeIn">
        <h1 class="mb-4 pb-0">{{ article.headline }}</h1>
        <p class="mb-4 pb-0">{{ article.sub_headline }}</p>
    </div>
    </section>

    <!-- start of post -->
    <div class="post-container">

        <!-- start article details -->
        <div class="article-info container">
          <div class="article-info-content display-center">
            <div class="display-center">
              <img class="author-pic" src="{{ article.author.profile_pic.url }}" alt="">
              <h6 class="author--text">By {{ article.author }} on {{ article.publish|date:"D M Y" }}</h6>
            </div>

            <div class="article-meta">
              <div class="tags">
                  {% for tag in article.tags.all %}
                  <span class="tag"><a href="#">{{ tag.name }}</a></span>
                  {% endfor %}
                  <a class="back-button" href="{% url 'blog:articles' %}">All Guides</a>
                  {% if user.is_authenticated and request.user.id == article.author.id %}
                    <a class="back-button" href="{% url 'blog:guide-update' article.slug %}">Update</a>
                    <a class="back-button" href="{% url 'blog:guide-delete' article.slug %}">Delete</a>
                  {% endif %}
              </div>
            </div>
          </div>
        </div>
        <!-- end of article details -->
        <hr>
        <p>{{ article.body|safe }}</p>
    </div>
    <!-- end of post -->
{% endblock %}

blog/templates/articles.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--==========================
    Intro Section
    ============================-->
    <section id="intro--article">
      <div class="intro-container wow fadeIn">
        <h1 class="mb-4 pb-0">Read the latest guides</h1>
        <a href="{% url 'blog:guide-create' %}" class="about-btn scrollto">Create guide</a>
      </div>
    </section>

    <section class="wow fadeIn">
        <div class = "container display-flex">
            <div class = "title">
              <h2>Guides</h2>
            </div>
            <div class="">
                <form method="GET">
                  <input type="text" id="query" name="query" class="textbox" placeholder="Search">
                  <button type = "submit" class="button">
                    <i class='bx bx-search'></i>
                  </button>
                </form>
                <div class="article-meta">
                    <a class="back-button" href="{% url 'blog:articles' %}">All Guides</a>
                    {% for tag in tags %}
                    <span class="tag"><a href="#">{{ tag.name }}</a></span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>

    <hr>

    <section class="wow fadeIn">
        <div class="container align-content-center">
            <div class = "featured-content">
              {% for article in articles %}
              <!-- item -->
              <div class = "featured-item">
                <div class = "featured-img">
                  <a href="{{ article.get_absolute_url }}">
                    <img class="img--1" src = "{{ article.image.url }}" alt = "">
                    <span><i class='bx bx-calendar-star'></i>{{ article.publish|date:"M Y" }}</span>
                    <span>{{ article.sub_headline }}</span>
                  </a>
                </div>
                <div class = "featured-title">
                  <a href = "{{ article.get_absolute_url }}">{{ article.headline }}</a>
                </div>
              </div>
              <!-- end of item -->
              {% empty %}
                      <h3>No Article found...</h3>
              {% endfor %}
            </div>
        </div>
    </section>

{% endblock %}

blog/templates/guide_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--==========================
        Intro Section
     ============================-->
    <section id="intro">
      <div class="intro-container wow fadeIn">
        <form method="POST" style="box-shadow: none;">
            {% csrf_token %}
            <p>Guide: {{ article.headline }}</p>
            <p>Are your sure you want to delete this guide? </p>
            <input  class="about-btn" style="color: black;" type="submit" value="Delete" />
            <a href="{% url 'blog:articles' %}" class="about-btn scrollto">Back</a>
        </form>
      </div>
    </section>
{% endblock %}

blog/templates/guide_form.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <!--==========================
        Intro Section
     ============================-->
      <section id="intro" style="height: 115vh;">
        <div class="intro-container wow fadeIn" style="">
          <div class="jumbotron" id="guide" style="">
              <p class="title" style="color: black;">Guide Creation</p>
                <form style="float: none; box-shadow: none; margin: 0;" method="POST">
                    {% csrf_token %}
                    {{ form.media }}

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Title</label>
                            {% render_field form.headline class='form-control input' %}
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Sub title</label>
                            {% render_field form.sub_headline class='form-control input' %}
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Guide cover photo: </label>
                            {% render_field form.image class='form-control-filet' %}
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">

                            {% render_field form.body class='form-control' %}
                        </div>
                    </div>
                    <input class="btn btn-primary" type="submit" value="Submit">
                </form>
                </div>
          </div>
        </div>
      </section>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--==========================
        Intro Section
     ============================-->
      <section id="intro">
        <div class="intro-container wow fadeIn">
          <h1 class="mb-4 pb-0">Create Share Discuss</h1>
          <p class="mb-4 pb-0">GUIDES BUILDS NEWS</p>
          <a href="#speakers" class="about-btn scrollto">Find out more</a>
        </div>
      </section>

    <main>
    <!--=========RECENT GUIDES=============-->

    <section id="speakers" class="wow fadeInUp">
      <div class="container">
        <div class="section-header">
          <h2>Latest guides</h2>
          <p>Here are the latest guides our users made</p>
        </div>

        <div class="row">
            {% for article in articles %}
            <!-- Guide -->
              <div class="col-lg-4 col-md-6">
                <div class="speaker">
                  <img src="{{ article.image.url }}" alt="" class="img-fluid">
                  <div class="details">
                    <h3><a href="{{ article.get_absolute_url }}">{{ article.headline }}</a></h3>
                    <p>{{ article.sub_headline }}</p>
                  </div>
                </div>
              </div>
            <!-- End of guide -->
            {% empty %}
			      <h3>No Featured Article at the Moment...</h3>
            {% endfor %}
        </div>
      </div>
    </section>

  <!--=========RECENT NEWS=============-->

  <section id="news" class="wow fadeInUp">
    <div class="news--style">
        <div class="container">
          <div class="section-header">
            <h2>Latest News</h2>
              <div class="twitter--content">
              <a class="twitter-timeline"
                 data-theme="light"
                 data-tweet-limit="4"
                 data-width = "100%"
                 style="margin-left: auto; margin-right: auto;"
                 href="https://twitter.com/PlaySoLOnline?ref_src=twsrc%5Etfw">Tweets by PlaySoLOnline
              </a>
              </div>
              <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          </div>
        </div>
    </div>
  </section>

    </main>


{% endblock %}

blog/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <!--==========================
        Intro Section
     ============================-->
      <section id="intro">
        <div class="intro-container wow fadeIn">
            <div class="jumbotron" style="margin: 1rem;">
                <p class="title" style="color: black;">Log in</p>
                <form method="POST" style="box-shadow: none; margin: 0;">
                    {% csrf_token %}

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Username</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="bi bi-person-circle"></i></span>
                                </div>
                                {% render_field form.username class='form-control input' %}
                            </div>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Password</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="bi bi-lock-fill"></i></span>
                                </div>
                                {% render_field form.password class='form-control input' %}
                            </div>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            {% for error in form.non_field_errors %}
                                <div class="alert alert-danger">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    </div>

                    <input class="btn btn-primary" type="submit" value="Login">
                </form>
            </div>
        </div>
      </section>
{% endblock %}

blog/templates/news.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!--==========================
    Intro Section
    ============================-->
    <section id="intro--article">
      <div class="intro-container wow fadeIn">
        <h1 class="mb-4 pb-0">Read the latest guides</h1>
        <p class="mb-4 pb-0"></p>
    </div>
    </section>

    <div class = "container align-content-center">
        <div class = "title">
          <h2>News</h2>
        </div>

        <hr>

        <div class = "featured-content">
          {% for article in articles %}
          <!-- item -->
          <div class = "featured-item">
            <div class = "featured-img">
              <a href="{{ article.get_absolute_url }}">
                <img class="img--1" src = "{{ article.image.url }}" alt = "">
                <span><i class='bx bx-calendar-star'></i>{{ article.publish|date:"M Y" }}</span>
                <span>{{ article.sub_headline }}</span>
              </a>
            </div>
            <div class = "featured-title">
              <a href = "{{ article.get_absolute_url }}">{{ article.headline }}</a>
            </div>
          </div>
          <!-- end of item -->
          {% empty %}
                  <h3>No Article found...</h3>
          {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/register.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block content %}
    <!--==========================
        Intro Section
     ============================-->
      <section id="intro">
        <div class="intro-container wow fadeIn">
            <div class="jumbotron" style="margin: 1rem;">
                <p class="title" style="color: black;">Registration</p>
                <form method="POST" style="box-shadow: none;">
                    {% csrf_token %}
                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Username:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="bi bi-person-circle"></i></span>
                                </div>
                                {% render_field form.username class='form-control input' placeholder='Enter your username' %}
                            </div>
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Password:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="bi bi-lock-fill"></i></span>
                                </div>
                                {% render_field form.password1 class='form-control input' %}
                            </div>
                            <small class="form-text">
                                Your password can’t be too similar to your other personal information.
                                <br>Your password must contain at least 8 characters.
                                <br>Your password can’t be a commonly used password.
                                <br>Your password can’t be entirely numeric.
                            </small>
                        </div>
                    </div>
                    <div class="form-row justify-content-center">
                        <div class="form-group col-md-12">
                            <label>Password confirmation:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="bi bi-lock-fill"></i></span>
                                </div>
                                {% render_field form.password2 class='form-control input' %}
                            </div>
                            <small class="form-text">
                                Enter the password again.
                            </small>
                        </div>
                    </div>

                    <div class="form-row justify-content-center">
                         <div class="form-group col-md-12">
                             {% for error in form.non_field_errors %}
                                 <div class="alert alert-danger">
                                     {{ error }}
                                 </div>
                             {% endfor %}
                         </div>
                    </div>

                    <input class="btn btn-primary" type="submit" value="Register">
                </form>
            </div>
        </div>
      </section>
{% endblock %}

blog/templates/review_message.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}


{% block content %}
    <!--==========================
        Intro Section
     ============================-->
      <section id="intro--each"
             style="background: url({{ article.image.url }}) top center; background-size: cover;">
      <div class="intro-container wow fadeIn">
        <h1 class="mb-4 pb-0">Your guide is under review</h1>
        <p class="mb-4 pb-0">It will be published momentarily</p>
        <a href="{% url 'blog:home' %}" class="about-btn scrollto">Home</a>
    </div>
    </section>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Solo Guide</title>
    <meta content="" name="keywords">
    <meta content="" name="description">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800" rel="stylesheet">

    <!-- Boxicon awesome icon -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    <!-- Bootstrap CSS File
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    -->
    <link href="{% static 'lib/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <!-- Libraries CSS Files -->
    <link href="{% static 'lib/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/animate/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'lib/venobox/venobox.css' %}" rel="stylesheet">
    <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style1.css' %}" rel="stylesheet">
</head>
<body>

  <!--====== HEADER ========-->

  <header id="header">
    <div class="container">

      <div id="logo" class="pull-left">
        <!-- Uncomment below if you prefer to use a text logo -->
        <!-- <h1><a href="#main">C<span>o</span>nf</a></h1>-->
        <a href="{% url 'blog:home' %}" class="scrollto"><img src="{% static 'img/book.png' %}" alt="" title=""></a>
      </div>

      <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="{% url 'blog:home' %}">Home</a></li>
          <li><a href="#">News</a></li>
          <li><a href="{% url 'blog:articles' %}">Guides</a></li>
          <li><a href="#schedule">Builds</a></li>

          {% if request.user.is_authenticated %}
            <li class="buy-tickets"><a href="#">{{request.user|title}}</a></li>
            <li class="buy-tickets"><a href="{% url 'blog:logout' %}">Logout</a></li>
          {% else %}
            <li class="buy-tickets"><a href="{% url 'blog:login' %}">Login</a></li>
            <li class="buy-tickets"><a href="{% url 'blog:register' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->


  <div>
      {% block content %}
      {% endblock %}
  </div>

  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <img src="img/logo.png" alt="SoloGuide">
            <p>This is a passion project and was started to practice coding and have fun with my friends</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="fa fa-angle-right"></i> <a href="#">Home</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">News</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Guides</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Builds</a></li>
            </ul>
          </div>


          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Check out Solo official media down below</h4>
            <div class="social-links">
              <a href="https://twitter.com/PlaySoLOnline" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="https://www.facebook.com/SwordsofLegendsOnline/" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="https://www.youtube.com/c/SwordsofLegendsOnline" class="youtube"><i class="fa fa-youtube"></i></a>
              <a href="https://www.twitch.tv/swordsoflegendsonline" class="twitch"><i class="fa fa-twitch"></i></a>
              <a href="https://www.instagram.com/swordsoflegendsonline/" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="https://discord.com/invite/joinSOLO" class="discord"><i class="fa fa-discord"></i></a>
            </div>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>Solo Guide</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
        -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <!-- JavaScript Libraries -->
  <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
  <script src="{% static 'lib/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'lib/easing/easing.min.js' %}"></script>
  <script src="{% static 'lib/superfish/hoverIntent.js' %}"></script>
  <script src="{% static 'lib/superfish/superfish.min.js' %}"></script>
  <script src="{% static 'lib/wow/wow.min.js' %}"></script>
  <script src="{% static 'lib/venobox/venobox.min.js' %}"></script>
  <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>
</body>
</html>